# Generated by Django 5.0.2 on 2024-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
